version: 2.1

jobs:
  build_and_test:
    docker:
      - image: cimg/node:19.8.1
    working_directory: ~/pantry-chef
    steps:
      - checkout
      - run: npm install
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Test
          command: npm run test
      - run:
          name: Build
          command: |
            echo "FIREBASE_API_KEY=$FIREBASE_API_KEY" >> .env
            npm run build
      - persist_to_workspace:
          root: ~/pantry-chef
          paths:
            - dist
  deploy:
    docker:
      - image: cimg/node:19.8.1
    working_directory: ~/pantry-chef
    steps:
      - attach_workspace:
          at: ~/pantry-chef
      - run:
          name: Deploy
          command: |
            sudo npm install -g netlify-cli
            netlify deploy --prod --dir=./dist --site=$NETLIFY_SITE_ID --auth=$NETLIFY_AUTH_TOKEN

workflows:
  build_test_deploy:
    jobs:
      - build_and_test
      - deploy:
          requires:
            - build_and_test # only deploy if the build_and_test job has completed
          filters:
            branches:
              only: main # only deploy when on main

